version: '3'
services:

  # certbot:
  #   image: certbot/dns-cloudflare
  #   volumes:
  #     - ./certbot_etc:/etc/letsencrypt
  #     - ./cloudflare.ini:/root/cloudflare.ini
  #   command: >-
  #     certonly --dns-cloudflare --dns-cloudflare-credentials /root/cloudflare.ini --dns-cloudflare-propagation-seconds 15 --email heyimjustalex@gmail.com --agree-tos --no-eff-email --force-renewal -d login.optykaoptometria.pl -d optykaoptometria.pl -d *.optykaoptometria.pl
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      #- certbot_etc:/etc/letsencrypt

volumes:
  certbot_etc:
