version: '3'
services:
  nginx:
    container_name: optykaoptometria
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
      # volumes:
      #   - ./nginx.conf:/etc/nginx/nginx.conf
      #    - ./ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      #- certbot_etc:/etc/letsencrypt

